version: '3.7'

services:
    mongo:
        image: mongo
        restart: always
        volumes:
            - mongo_db_data:/data/db
        ports:
            - "27017:27017"

volumes:
    mongo_db_data:
        driver: local